name: QA
on: [ pull_request, push ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1
  phpunit:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Run phpunit
        run: ./vendor/bin/phpunit --group extended,default --teamcity
  psalm:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Run psalm
        run: ./vendor/bin/psalm
  phpstan:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Run phpstan
        run: ./vendor/bin/phpstan